export const FETCH_CURRENT_DATA = "FETCH_CURRENT_DATA";
export const FETCH_HISTORICAL_DATA = "FETCH_HISTORICAL_DATA";
export const SET_MAIN_TABLE_DATA = "SET_MAIN_TABLE_DATA";
export const SET_MAP_DATA = "SET_MAP_DATA";
export const SET_TOP_FIVE_TABLE = "SET_TOP_FIVE_TABLE";
export const FETCH_STATE_DATA = "FETCH_STATE_DATA";
export const LOADING_TRUE = "LOADING_TRUE";
export const LOADING_FALSE = "LOADING_FALSE";
export const FETCH_SELECTED_STATE_CURRENT_DATA =
  "FETCH_SELECTED_STATE_CURRENT_DATA";
export const RESET_STATE = "RESET_STATE";
export const FETCH_CDC_PROVIDSIONAL_DATA = "FETCH_CDC_PROVIDSIONAL_DATA";
