export const FETCH_CURRENT_DATA = "FETCH_CURRENT_DATA";
export const FETCH_HISTORICAL_DATA = "FETCH_HISTORICAL_DATA";
export const SET_MAIN_TABLE_DATA = "SET_MAIN_TABLE_DATA";
export const SET_MAP_DATA = "SET_MAP_DATA";
export const SET_TOP_FIVE_TABLE = "SET_TOP_FIVE_TABLE";
export const LOADING = "LOADING";
